export const metadata = {
  title:"Next.js",
  description:"Generated by next.js"
}
export default function ProductsDetailsLayout({
  children,
}:{
  children:React.ReactNode
}){
  return (
    <>
      {children}
      <h2>Features products</h2>
    </>
  )
}